### ISSUE TITLE
get version information via function

### ISSUE THREAD

**Issue by Trybnetic** [quantling/pyndl#116]
We should provide a function to show information about the system, the installed packages, etc. like in [pandas](https://github.com/pandas-dev/pandas/blob/master/pandas/_version.py).

This may especially useful for issue reporting as it is much more precise than `pip freeze`

**Comment by derNarr** [comment]
Copied from PR #111, we can and should be very close to the pandas way of doing it:

We might want to supply a function within pyndl that greps the most important information for us and prints it to the stdout in order to copy it here.

For example:

```
pyndl.sysinfo()
```

Should include:

- pyndl version
- numpy version
- python version
- os version
- xarray version
- pandas version
- available memory
- available diskspace in tmp
- ???
