### ISSUE TITLE
Installation instructions do not specify Python headers are needed

### ISSUE THREAD

**Issue by frankier** [quantling/pyndl#211]
This issue is part of my [JOSS review](https://github.com/openjournals/joss-reviews/issues/4515).

The installation instructions do not specify that a successful installation requires the Python C headers (these are included in  python-dev in Debian for example).

**Comment by derNarr** [comment]
I always felt they come with a proper `cython` installation but it does not hurt to add them into our documentation as well. I will think about where to place this information best. If you have any suggestion, where you would expect this, let me know as well. Thanks!

Here? https://pyndl.readthedocs.io/en/latest/installation.html

**Comment by frankier** [comment]
> I always felt they come with a proper cython installation

I don't think so, but I'm not 100% on that. Probably if you install Cython through the OS package manager it will pull in the headers, but I don't think Python headers have ever been packaged through PyPI (maybe they should be -- but it would also probably involve somehow hooking into the build process so the path would be passed through).

I did get an actual error about missing header files during installation since I happened to not have them installed for the version of Python I tested with. The normal instructions for Debian -like distributions is `build-essential python3-dev`. There may be some instructions somewhere you can link to or reuse e.g. https://py-generic-project.readthedocs.io/en/latest/installing.html -- although that guide seems to miss out that you (?maybe?) need to install Visual C++ on Windows. For most Python programmers this is old hat, but the audience for this package could include corpus linguists who may be Python beginners. Also it's more common for people to not have them installed now there are so many wheels available.

> Here? https://pyndl.readthedocs.io/en/latest/installation.html

Yes you can put the full instructions there and then note in the "Installation" section of the README something like that it is "assuming you have already installed the requirement to compile Python extensions" and direct to the full instructions. If you upload wheels you could omit this in the README since usually people will be able to install the wheel (but there are various reasons they may have to fall back to a source installation).

**Comment by frankier** [comment]
This appears to have come up before https://github.com/quantling/pyndl/issues/187 (I did not find this issue when searching previously since it's a bit vague)

**Comment by derNarr** [comment]
As far as I understand this, it boils down to the ability to properly compile Python extensions with Cython. In order to be able to properly compile these extensions Cython, Python headers and a C compiler like gcc or clang need to be installed. If you use a scientific Python distribution like Miniconda this distribution seems to taken care of the necessary steps, e.g. running `conda install cython` should give you all you need to properly compile extensions.

With the next update of `pyndl` this will be pointed out more clearly in the documentation. Furthermore, we added wheels (for Linux), which does not need the compile step at all.

This issue will be closed, when the pull request is merged that adds the information to the documentation. @frankier if you feel I missed an important aspect, please reopen the issue and point out what is missing. Thank you! :-)

**Comment by frankier** [comment]
Great! ☑
